bcachefs: Fix build error with clang
src/fs/bcachefs/io_write.c:1488:2: error: label followed by a declaration is a C23 extension [-Werror,-Wc23-extensions]
 1488 |         CLASS(printbuf, buf)();
      |         ^
/usr/lib/modules/6.17.0-1-mainline-dirty/build/include/linux/cleanup.h:290:2: note: expanded from macro 'CLASS'
  290 |         class_##_name##_t var __cleanup(class_##_name##_destructor) =   \
      |         ^
<scratch space>:74:1: note: expanded from here
   74 | class_printbuf_t
      | ^

Fixes: 5a0ea9850f9f ("bcachefs: Convert nocow write path to new nocow locking helpers")
Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>