Fixup time namespace build
`<linux/hrtimer.h>` was changed to include `<linux/percpu-defs.h>`
instead of `<linux/percpu.h>` and now `vm_area_struct` is not declared
before `#include <linux/time_namspace.h>`, which leads to
```
  CC      kernel/time/namespace.o
In file included from kernel/time/namespace.c:7:
./include/linux/time_namespace.h:48:43: warning: ‘struct vm_area_struct’ declared inside parameter list will not be visible outside of this definition or declaration
   48 | struct page *find_timens_vvar_page(struct vm_area_struct *vma);
      |                                           ^~~~~~~~~~~~~~
kernel/time/namespace.c:195:14: error: conflicting types for ‘find_timens_vvar_page’; have ‘struct page *(struct vm_area_struct *)’
  195 | struct page *find_timens_vvar_page(struct vm_area_struct *vma)
      |              ^~~~~~~~~~~~~~~~~~~~~
./include/linux/time_namespace.h:48:14: note: previous declaration of ‘find_timens_vvar_page’ with type ‘struct page *(struct vm_area_struct *)’
   48 | struct page *find_timens_vvar_page(struct vm_area_struct *vma);
      |              ^~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:252: kernel/time/namespace.o] Error 1
```

Add declaration to the `<linux/time_namespace.h>` to fix it.

Fixes: 53e51876a2aa25b1150519436bc5f8b5e768413f
Signed-off-by: ojab <ojab@ojab.ru>